const clothingItems = [
  {
    id: 1,
    name: "Classic White T-Shirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black", "Grey"],
    price: 19.99,
    description: "A classic white t-shirt made from 100% organic cotton.",
    material: "100% Cotton",
    stock: 120,
    images: [
      "https://i.postimg.cc/6QQh9366/white-front.png",
      "https://i.postimg.cc/CKLVSjfZ/Screenshot-2024-07-27-101056.png",
    ],
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Blue", "Black", "Grey"],
    price: 49.99,
    description: "Stylish slim fit jeans with a modern look.",
    material: "98% Cotton, 2% Elastane",
    stock: 75,
    images: [
      "https://i.postimg.cc/6QQh9366/white-front.png",
      "https://i.postimg.cc/yYQGcwJN/Screenshot-2024-07-27-101413.png",
    ],
  },
  {
    id: 3,
    name: "Floral Summer Dress",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Blue", "Yellow"],
    price: 39.99,
    description: "A beautiful floral summer dress perfect for sunny days.",
    material: "100% Polyester",
    stock: 50,
    images: [
      "https://i.postimg.cc/Dfsj8ShB/Screenshot-2024-07-27-101544.png",
      "https://i.postimg.cc/Dfsj8ShB/Screenshot-2024-07-27-101544.png",
    ],
  },
  {
    id: 4,
    name: "Men's Leather Jacket",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Brown"],
    price: 129.99,
    description: "Premium quality leather jacket for men.",
    material: "100% Genuine Leather",
    stock: 30,
    images: [
      "https://i.postimg.cc/fT1r81sT/Screenshot-2024-07-27-101740.png",
      "https://i.postimg.cc/KjMHb5ry/Screenshot-2024-07-27-101750.png",
    ],
  },
  {
    id: 5,
    name: "Comfy Hoodie",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Black", "Navy Blue"],
    price: 29.99,
    description: "A cozy and comfortable hoodie made from soft fabric.",
    material: "60% Cotton, 40% Polyester",
    stock: 100,
    images: [
      "https://i.postimg.cc/5ymb11mJ/Screenshot-2024-07-27-101936.png",
      "https://i.postimg.cc/g2840JZ3/Screenshot-2024-07-27-101955.png",
    ],
  },

  {
    id: 6,
    name: "Casual Chinos",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Beige", "Navy Blue", "Olive"],
    price: 34.99,
    description: "Comfortable and stylish chinos for casual wear.",
    material: "100% Cotton",
    stock: 80,
    images: [
      "https://i.postimg.cc/zvpwhbkc/Screenshot-2024-07-27-102155.png",
      "https://i.postimg.cc/nh97FwN5/Screenshot-2024-07-27-102213.png",
    ],
  },
  {
    id: 7,
    name: "Striped Polo Shirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red/White", "Blue/White", "Green/White"],
    price: 24.99,
    description: "A stylish striped polo shirt made from breathable fabric.",
    material: "100% Cotton",
    stock: 90,
    images: [
      "https://i.postimg.cc/6TJKdq5C/Screenshot-2024-07-27-102320.png",
      "https://i.postimg.cc/htKjwZcT/Screenshot-2024-07-27-102330.png",
    ],
  },
  {
    id: 8,
    name: "Women's Cardigan",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Black", "Pink"],
    price: 44.99,
    description: "A soft and warm cardigan for women.",
    material: "80% Wool, 20% Acrylic",
    stock: 40,
    images: [
      "https://i.postimg.cc/15C2hfZB/Screenshot-2024-07-27-102458.png",
      "https://i.postimg.cc/ydHrXRF1/Screenshot-2024-07-27-102505.png",
    ],
  },
];

export default clothingItems;
